# Generated by Django 4.2.5 on 2023-09-18 14:34

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import social.models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=100, scale=None, size=[600, 400], upload_to=social.models.get_image_file)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='social.post')),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['-created'], name='social_imag_created_84e743_idx')],
            },
        ),
    ]
