# Generated by Django 4.2.5 on 2023-11-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_post_total_likes_post_social_post_total_l_b22ce0_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
